# Introduction to Tensors

In the language of deep learning, a tensor can be anything from a number(scaler) to a vector, matrix or any n-dimensional array.

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Creating Tensors

In [2]:
# Scalers
scaler = torch.tensor(6)
print(scaler)
print(scaler.dtype)

tensor(6)
torch.int64


In [3]:
# Vectors - also known as column matrices
vector = torch.tensor([1.3, 3.2, 2.5, 9])
print(vector)

tensor([1.3000, 3.2000, 2.5000, 9.0000])


In [4]:
# Matrices
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
matrix

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [5]:
# Checking the dimension of a tensor
matrix.ndim

2

In [6]:
# 3-dimensional array
array_3d = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9.4]]])
array_3d

tensor([[[1.0000, 2.0000, 3.0000],
         [4.0000, 5.0000, 6.0000],
         [7.0000, 8.0000, 9.4000]]])

In [7]:
array_3d.shape

torch.Size([1, 3, 3])

In [8]:
array_3d.dtype

torch.float32

In [9]:
array_3d[0]

tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.0000],
        [7.0000, 8.0000, 9.4000]])

In [10]:
# Creating random tensors
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)

tensor([[0.3155, 0.2344, 0.3742, 0.4177],
        [0.3578, 0.9426, 0.1736, 0.9521],
        [0.2492, 0.6537, 0.6768, 0.8372]])


## Tensor aggregation - `mean`, `max`, `min`, `sum`

In [11]:
# Create a tensor
x = torch.arange(-3, 20, 2)
x

tensor([-3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
# Find the min
x.min()

tensor(-3)

In [13]:
# Find the max
x.max()

tensor(19)

In [14]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(8.)

In [15]:
# Find the sum
torch.sum(x)

tensor(96)

## Reshaping

In [16]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Reshape to a 2-d tensor
x.reshape(3, 3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Tensor Operation and Gradient

In [39]:
x = torch.tensor(3., requires_grad=True)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5.,)

In [40]:
# Arithmetic operation
y = w * (x**2) + b
y

tensor(41., grad_fn=<AddBackward0>)

In [41]:
# Compute derivatives
y.backward()

In [42]:
print(f'dy/dx: {x.grad}')
print(f'dy/dw: {w.grad}')
print(f'dy/db: {b.grad}')

dy/dx: 24.0
dy/dw: 9.0
dy/db: None
